[package]
name = "sol2"
version = "0.1.0"
edition = "2024"

[dependencies]
criterion = { version = "0.7.0", features = ["html_reports"] }
memmap2 = "0.9.9"
rayon = "1.11.0"
findlib = { path = "../findlib" }

[[bench]]
name = "bench"
harness = false